### ISSUE TITLE
npm ERR! 404 Not Found: Package from private NPM Registry

### ISSUE THREAD

**Issue by JohnOllhorn** [openfaas/faas#1025]
Hello folks!

## Expected Behaviour
Allow privates NPM Repository in faas-cli build

## Current Behaviour

We use a private npm registry for our Node.js packages.
Unfortunately we get an error message when building our OpenFaas function:

```bash
npm ERR! code E404
npm ERR! 404 Not Found: <npm-package>@^1.33.7

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-11T13_50_17_699Z-debug.log
```
```bash
Error: Cannot find module '<NPM-PACKAGE>'
 2019/01/11 13:30:08 Error reading stderr: EOF
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
     at Function.Module._load (internal/modules/cjs/loader.js:529:25)
     at Modu
     at Modu
 2019/01/11 13:30:01 stderr: le.require (internal/modules/cjs/loader.js:657:17)
 2019/01/11 13:29:41 stderr: le.require (internal/modules/cjs/loader.js:657:17)
     at require (internal/modules/cjs/helpers.js:22:18)
     at require (internal/modules/cjs/helpers.js:22:18)
     at Object.<anonymous> (/home/app/function/handler.js:2:16)
     at Object.<anonymous> (/home/app/function/handler.js:2:16)
     at Module._compile (internal/modules/cjs/loader.js:721:30)
     at Object.Module._ex
 2019/01/11 13:29:41 stderr: tensions..js (internal/modules/cjs/loader.js:732:10)
     at require (internal/modules/cjs/helpers.js:22:18)
     at Module.load (internal/modules/cjs/loader.js:620:32)
     at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
     at Object.<anonymous> (/home/app/function/handler.js:2:16)
     at Function.Module._load (internal/modules/cjs/loader.js:552:3)
     at Module._compile (internal/modules/cjs/loader.js:721:30)
```

The problem is theoretically known, but practically somehow cannot be solved without help. :)

We get these two commands into the build process of faas-cli ?

```bash
npm set registry https://<NPM-REGISTRY>
npm adduser --registry https://<NPM-REGISTRY>
```

Unfortunately our .npmrc, which is supposed to define something like this, is not used...

## Possible Solution

```bash
npm set registry https://<NPM-REGISTRY>
npm adduser --registry https://<NPM-REGISTRY>
```

## Steps to Reproduce (for bugs)

1. Uses a private NPM package in a Node.js app
2.
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```bash
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  5b36c50280d961d3aa248bd17f901f4ef2774447
 version: 0.8.1
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):
```bash
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:31 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm
* Operating System and version (e.g. Linux, Windows, MacOS):
Linux
* Link to your project or a code example to reproduce issue:
Link only on request per PM
* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by JohnOllhorn** [comment]
Oky after a short think... it is quite clear!

I adjusted the dockerfile:
```bash
# COPY function node packages and install, adding this as a separate
# entry allows caching of npm install
WORKDIR /home/app/function

COPY function/.npmrc ./                         # <--------------------- :)

COPY function/*.json ./
RUN npm i || :
```
Also tested, works for me.

I'll leave it there, maybe someone else could use it.

**Comment by burtonr** [comment]
You could do a PR for the node template(s) in the [templates repo](https://github.com/openfaas/templates) :smile:

**Comment by rgee0** [comment]
@JohnOllhorn you'll likely want to `rm` your .npmrc once you've completed `npm i`
