### ISSUE TITLE
/system/info endpoint returns nil fields on ARMHF

### ISSUE THREAD

**Issue by rgee0** [openfaas/faas#1040]
## Expected Behaviour
Using `faas-cli version` against an `armhf` gateway should not panic.  It should provide the expected information in the same way as x86_64 does.
```
$ faas version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  5b36c50280d961d3aa248bd17f901f4ef2774447
 version: 0.8.1

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.9.11
 sha:     78a4584019a2a5d86b606a00b4fba979930cc2a7
 commit:  Add sha256 hashgen for watchdog to ci config


Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.5.0 
 sha:           4269ab15673ad883bfdce4df47c055588e8e86b2
```

Accessing http://<OPENFAAS_URL>:8080/system/info returns:

```
{"provider":{"provider":"faas-swarm","version":{"sha":"4269ab15673ad883bfdce4df47c055588e8e86b2","release":"0.5.0"},"orchestration":"swarm"},"version":{"commit_message":"Add sha256 hashgen for watchdog to ci config","sha":"78a4584019a2a5d86b606a00b4fba979930cc2a7","release":"0.9.11"}}
```

## Current Behaviour

An ungraceful error is returned.

```
$ faas version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  a141dedf94ffeed84412365fd591bdc8999c5a1b
 version: 0.8.3
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/openfaas/faas-cli/commands.getGatewayDetails(...)
	/go/src/github.com/openfaas/faas-cli/commands/version.go:120
github.com/openfaas/faas-cli/commands.printServerVersions()
	/go/src/github.com/openfaas/faas-cli/commands/version.go:78 +0x42c
github.com/openfaas/faas-cli/commands.runVersion(0x640d68, 0x653e90, 0x0, 0x0)
	/go/src/github.com/openfaas/faas-cli/commands/version.go:54 +0x144
github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra.(*Command).execute(0x640d68, 0x653e90, 0x0, 0x0, 0x640d68, 0x653e90)
	/go/src/github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra/command.go:766 +0x20c
github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x63e898, 0x0, 0x3fc780, 0x18e4b80)
	/go/src/github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra/command.go:852 +0x210
github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x63e898, 0x6, 0x388dd1)
	/go/src/github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra/command.go:800 +0x1c
github.com/openfaas/faas-cli/commands.Execute(0x18f6250, 0x2, 0x2)
	/go/src/github.com/openfaas/faas-cli/commands/faas.go:77 +0x90
main.main()
	/go/src/github.com/openfaas/faas-cli/app.go:19 +0x64
```
Accessing http://<OPENFAAS_URL>:8080/system/info returns:

```
{"provider":{"provider":"faas-swarm","version":{"sha":"4269ab15673ad883bfdce4df47c055588e8e86b2","release":"0.5.0"},"orchestration":"swarm"},"version":{"sha":"","release":"dev"}}
```

## Possible Solution
The `/system/info/` endpoint is missing key information on `armhf`.  The contents of `Dockerfile.armhf` could be updated to more closely match that of `Dockerfile` including the build-args and license check at 0.2.3.

## Steps to Reproduce (for bugs)
1. Clone repo onto an ARM32 machine
2. Run `./deploy_stack.armhf.sh`
3. `curl -sSL https://cli.openfaas.com | sudo sh`
4. `faas version`

## Context
Inconsistent experience
Ugly error message

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
$ faas version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  a141dedf94ffeed84412365fd591bdc8999c5a1b
 version: 0.8.3
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/openfaas/faas-cli/commands.getGatewayDetails(...)
	/go/src/github.com/openfaas/faas-cli/commands/version.go:120
github.com/openfaas/faas-cli/commands.printServerVersions()
	/go/src/github.com/openfaas/faas-cli/commands/version.go:78 +0x42c
github.com/openfaas/faas-cli/commands.runVersion(0x640d68, 0x653e90, 0x0, 0x0)
	/go/src/github.com/openfaas/faas-cli/commands/version.go:54 +0x144
github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra.(*Command).execute(0x640d68, 0x653e90, 0x0, 0x0, 0x640d68, 0x653e90)
	/go/src/github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra/command.go:766 +0x20c
github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x63e898, 0x0, 0x3fc780, 0x18e4b80)
	/go/src/github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra/command.go:852 +0x210
github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x63e898, 0x6, 0x388dd1)
	/go/src/github.com/openfaas/faas-cli/vendor/github.com/spf13/cobra/command.go:800 +0x1c
github.com/openfaas/faas-cli/commands.Execute(0x18f6250, 0x2, 0x2)
	/go/src/github.com/openfaas/faas-cli/commands/faas.go:77 +0x90
main.main()
	/go/src/github.com/openfaas/faas-cli/app.go:19 +0x64
```

* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
 docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:57:21 2018
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:17:57 2018
  OS/Arch:          linux/arm
  Experimental:     false
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Raspbian

**Comment by alexellis** [comment]
Are all your versions up to date?

Have you narrowed down the cause of the error yet? I don't remember seeing it on arm when I tested recently.

**Comment by alexellis** [comment]
Derek assign: ewilde

**Comment by rgee0** [comment]
Yes, as above the Dockerfile is wrong.  I've fixed it, just PRing

**Comment by alexellis** [comment]
Thank you! How is ARM64?

**Comment by alexellis** [comment]
Derek assign: rgee0

**Comment by rgee0** [comment]
> Thank you! How is ARM64?
Just as broken

**Comment by rdimitrov** [comment]
Started a Swarm on both on ARMHF and ARM64 and it seems to be working okay as I didn't saw the output referenced in the description.
