### ISSUE TITLE
Unit tests fail on armhf 

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas#1063]
## Expected Behaviour

The gateway unit tests should pass on armhf (Raspberry Pi)

## Current Behaviour

They currently fail 100% of the time due to the Prometheus exporter integration tests due to a "closed channel" error. This happened after upgrading the Prometheus go client, but may be related to timing.

You can also reproduce the error on a regular PC intermittently

**Comment by rosti** [comment]
From last run by @rdimitrov :
```
/... | grep -v integration | grep -v /vendor/ | grep -v /template/) -cover     && CGO_ENABLED=0 GOOS=linux go build --ldflags "-s -w     -X github.com/openfaas/faas/gateway/version.GitCommitSHA=${GIT_COMMIT_SHA}    -X \"github.com/openfaas/faas/gateway/version.GitCommitMessage=${GIT_COMMIT_MESSAGE}\"    -X github.com/openfaas/faas/gateway/version.Version=${VERSION}"     -a -installsuffix cgo -o gateway .
 ---> Running in d4bacfddac9e
?       github.com/openfaas/faas/gateway    [no test files]
ok      github.com/openfaas/faas/gateway/handlers   0.006s  coverage: 28.9% of statements
PASS
coverage: 43.9% of statements
panic: send on closed channel
goroutine 21 [running]:
github.com/openfaas/faas/gateway/vendor/github.com/prometheus/client_golang/prometheus.(*metricMap).Describe(...)
    /go/src/github.com/openfaas/faas/gateway/vendor/github.com/prometheus/client_golang/prometheus/vec.go:222
github.com/openfaas/faas/gateway/metrics.(*Exporter).Describe(0xc420172240, 0xc420174360)
    /go/src/github.com/openfaas/faas/gateway/metrics/exporter.go:45 +0xce
created by github.com/openfaas/faas/gateway/metrics.Test_Describe_DescribesThePrometheusMetrics
    /go/src/github.com/openfaas/faas/gateway/metrics/exporter_test.go:41 +0x17d
FAIL    github.com/openfaas/faas/gateway/metrics    0.009s
ok      github.com/openfaas/faas/gateway/plugin 0.010s  coverage: 81.4% of statements
?       github.com/openfaas/faas/gateway/queue  [no test files]
ok      github.com/openfaas/faas/gateway/requests   0.021s  coverage: 75.0% of statements
ok      github.com/openfaas/faas/gateway/scaling    0.037s  coverage: 24.6% of statements
ok      github.com/openfaas/faas/gateway/types  0.015s  coverage: 81.8% of statements
?       github.com/openfaas/faas/gateway/version    [no test files]
The command '/bin/sh -c license-check -path ./ --verbose=false "Alex Ellis" "OpenFaaS Project" "OpenFaaS Authors" "OpenFaaS Author(s)"     && test -z "$(gofmt -l $(find . -type f -name '*.go' -not -path "./vendor/*"))"     && go test $(go list ./... | grep -v integration | grep -v /vendor/ | grep -v /template/) -cover     && CGO_ENABLED=0 GOOS=linux go build --ldflags "-s -w     -X github.com/openfaas/faas/gateway/version.GitCommitSHA=${GIT_COMMIT_SHA}    -X \"github.com/openfaas/faas/gateway/version.GitCommitMessage=${GIT_COMMIT_MESSAGE}\"    -X github.com/openfaas/faas/gateway/version.Version=${VERSION}"     -a -installsuffix cgo -o gateway .' returned a non-zero code: 1
make: *** [ci-armhf-build] Error 1
```

This [`defer close(ch)`](https://github.com/openfaas/faas/blob/b4a550327d6bddfb5a5316636e19a288345296c3/gateway/metrics/exporter_test.go#L39) is in a race with the go routine started a couple of lines further down.
You have 3 reads from the channel before the exit of the test func (which will close the channel), but in the go routine you invoke the [`Describe`](https://github.com/openfaas/faas/blob/b4a550327d6bddfb5a5316636e19a288345296c3/gateway/metrics/exporter.go#L39) function, that invokes 5 other `Describe`s each writing something. Thus, the last 2 channel writes are in a race with the close of the channel.

```
	e.metricOptions.ServiceMetrics.Counter.Describe(ch)
	e.metricOptions.ServiceMetrics.Histogram.Describe(ch)
```

Ways to fix this:

1. Don't close the channel.
2. Don't use a go routine.
3. Is this test doing what you need? Could be that it's outdated and in a need of rewriting.

I am surprised that it actually happens to work so often. I would expect almost 100% crash rate on a modern machine.

**Comment by zeerorg** [comment]
I was able to workaround this by just removing `defer close(ch)`

```
diff --git a/gateway/metrics/exporter_test.go b/gateway/metrics/exporter_test.go
index 9a23a3cd..487e1565 100644
--- a/gateway/metrics/exporter_test.go
+++ b/gateway/metrics/exporter_test.go
@@ -36,7 +36,6 @@ func Test_Describe_DescribesThePrometheusMetrics(t *testing.T) {
        exporter := NewExporter(metricsOptions, nil)

        ch := make(chan *prometheus.Desc)
-       defer close(ch)

        go exporter.Describe(ch)
```

@rosti is right about the race condition, still don't know why it works on any other architecture.

**Comment by rdimitrov** [comment]
Thank you, guys! 👍 
Tested your patch on ARMHF where it was failing on almost every build and it was working, so I created a PR based on your suggestions.
