### ISSUE TITLE
faas node: context.succeed is not a function

### ISSUE THREAD

**Issue by dcolley** [openfaas/faas#1471]
## My actions before raising this issue
- [x] Followed the [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting/)
- [x] Read/searched [the docs](https://docs.openfaas.com/)
- [x] Searched [past issues](/issues)

I followed https://docs.openfaas.com/cli/templates/

## Expected Behaviour

No errors:
```
    context
        .succeed(result)
        .status(201)
```

## Current Behaviour

```
TypeError: context.succeed is not a function
    at module.exports (/home/app/function/handler.js:25:10)
    at /home/app/index.js:25:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## Steps to Reproduce (for bugs)

1. handler.js
```
'use strict'

module.exports = (event, context) => {
    let err;
    const result = {
        status: "Received input: " + JSON.stringify(event.body),
    };

    context
        .succeed(result)
        .status(201)
}
```

2. test.yml
```
version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  auth-token:
    lang: node
    handler: ./auth-token
    image: derekc/auth-token:latest
    environment:
      write_debug: true
```
3.
4.

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
```
faas-cli version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  ea687659ecf14931a29be46c4d2866899d36c282
 version: 0.11.8

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.18.11
 sha:     326cc7a9b9235276ecf38430c49a5707a429c6c8
 commit:  Add featured videos section to community file


Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.8.2 
 sha:           47988f8ba284678f3eb86eb62f75f72bafeec4d9
```
* Docker version `docker version` (e.g. Docker 17.0.05 ):
```
docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
`Docker Swarm`
* Operating System and version (e.g. Linux, Windows, MacOS):
`MaxOS`
* Code example or link to GitHub repo or gist to reproduce problem:
`as above`
* Other diagnostic information / logs from [troubleshooting guide](https://docs.openfaas.com/deployment/troubleshooting)

## Next steps

You may [join Slack](https://docs.openfaas.com/community) for community support.

**Comment by dcolley** [comment]
I am trying to 
- determine if POST or GET was invoked
- manipulate the response headers

**Comment by dcolley** [comment]
managed to solve my own problem...
use `lang: node8-express` in the yml file

then I can see the event contains:
```javascript
{
    "event": {
        "body": {
            "app_id": "123",
            "app_secret": "456"
        },
        "headers": {
            "host": "auth-token:8080",
            "user-agent": "PostmanRuntime/7.22.0",
            "transfer-encoding": "chunked",
            "accept": "*/*",
            "accept-encoding": "gzip, deflate, br",
            "cache-control": "no-cache",
            "content-type": "application/json",
            "postman-token": "89fcfab0-55c9-4f8f-b486-d0616b83e4bf",
            "x-call-id": "f6076922-3776-4f59-a298-7a691ae97950",
            "x-forwarded-for": "10.0.0.2:58076",
            "x-forwarded-host": "127.0.0.1:8080",
            "x-start-time": "1583600481071409400"
        },
        "method": "POST",
        "query": {},
        "path": "/"
    }
}
```

I got that from this video 
https://www.youtube.com/watch?v=uZPXwuKxsEU

**Comment by alexellis** [comment]
Hi @dcolley the issue was that you were using the wrong template.

You should not use Node.js 8, that repo has been archived. The LTS version of Node.js is 12, use the `node12` template instead, which is documented in the link you shared at docs.openfaas.com

Alex
